### ISSUE TITLE
week 01 回覆

### ISSUE THREAD

**Issue by azole** [ChenTim1011/git-practice#1]
- 你把我的名字寫錯了喔 XD
- 所以你後來有加選嗎？

git.md 有在 week 2 下課後再做過調整對嗎？ 以調整過後的來說，非常不錯，也有提出自己的疑問，整學期...應該說，整個工程師生涯，都要保持這樣的好奇心，繼續努力。

關於 video.md 中你提到開始建立錯誤日記，這點真的是太棒了，我經常跟學生分享，在學習的過程中，犯錯是好事，這樣說好了，如果沒有犯錯、順順地做過去，人的大腦天生是懶惰的，這麼順利就不會去主動思考，只有在犯錯的時候，才會開始刺激大腦去想到底怎麼了，再來是犯錯時去查資料、去跟同學老師請教，往往會獲得比原本的題目更多的知識。所以，如果能從錯誤中學習，犯錯其實是一件很棒的事，退一萬步講，學習時犯錯，總比工作時犯錯還要好吧？

> 沒辦法一下子就變很厲害，但重要是持續變好，往正確的道路上

這學期你就試著持續一學期看看，要給自己機會建立「成功的案例」，之後你就會愈來愈相信自己的。

**Comment by ChenTim1011** [comment]
Q1: 不好意思竟然犯了這個錯誤QQ
Q2: 後來有加簽上了謝謝老師。
Q3: 沒錯  git.md 有在 week 2 下課 ，上課聽到有什麼建議，會想要去修改過去的作業，把過去的作業做得更好一點。

謝謝老師的鼓勵! 我很開心，我過去的學習態度沒有很好，造成現在實作能力比其他系上同學差，但我希望這學期的課程可以是我的轉捩點，也希望我可以繼續堅持下去，持續進步。

**Comment by azole** [comment]
任何人在任何時候，都可以重新開始努力，偷偷跟你說，我大學的時候也很萌懂，我沒有不乖，但真的不知道努力的方向跟標準，也不積極。我比你不幸運、但也比很多人幸運，我是在進入職場後，遇到很多願意指點我的前輩，有的也不是直接指點，就是他們做得很好，也不藏私，願意讓我在旁邊偷偷觀察，一直走到今天，我都覺得還有超級多東西要學的。

所以鼓勵你，只要開始就永遠不晚，你開始得還比我早了，上課多參與、多動腦，課前課後多花時間，永遠不會白費的，除了課堂上直接的輸出輸入外，也要刻意地去觀察其他人，不管做得好或不夠好，好的、也覺得適合自己就學習，看到不夠好的，就檢視自己避免這樣做，一但刻意觀察後會發現，超級多地方可以學習的。

**Comment by azole** [comment]
如果沒有其他要聊的，那個 issue 就可以先關閉了。
